# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deepconclusions',
                'doc_host': 'https://deepconclusions.github.io',
                'git_url': 'https://github.com/deepconclusions/deepconclusions',
                'lib_path': 'deepconclusions'},
  'syms': {'deepconclusions.core': {'deepconclusions.core.foo': ('core.html#foo', 'deepconclusions/core.py')}}}
