project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    right:
      - text: Home
        href: "https://www.deepconclusions.com/"
      - text: About
        href: "https://www.deepconclusions.com/about"
      - text: Blog
        href: "https://deepconclusions.com/blogs"
      - text: Contact
        href: "https://deepconclusions.com/contact"
  sidebar:
    style: "floating"
    twitter-card:
    creator: "@juma_shafara"
    site: "@datas_idea"

metadata-files: [nbdev.yml, sidebar.yml]
